[2023-12-26T11:36:08.292+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project_dag.create_time_table manual__2023-12-26T11:31:00.224027+00:00 [queued]>
[2023-12-26T11:36:08.339+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project_dag.create_time_table manual__2023-12-26T11:31:00.224027+00:00 [queued]>
[2023-12-26T11:36:08.340+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 4
[2023-12-26T11:36:08.436+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_time_table> on 2023-12-26 11:31:00.224027+00:00
[2023-12-26T11:36:08.456+0000] {standard_task_runner.py:60} INFO - Started process 17261 to run task
[2023-12-26T11:36:08.466+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'create_time_table', 'manual__2023-12-26T11:31:00.224027+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/final_project/final_project.py', '--cfg-path', '/tmp/tmpyrkxso9d']
[2023-12-26T11:36:08.470+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask create_time_table
[2023-12-26T11:36:08.602+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project_dag.create_time_table manual__2023-12-26T11:31:00.224027+00:00 [running]> on host d3aa51350085
[2023-12-26T11:36:08.739+0000] {abstractoperator.py:708} ERROR - Exception rendering Jinja template for task 'create_time_table', field 'sql'. Template: 'create_time_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_time_table.sql
[2023-12-26T11:36:08.741+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2335, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2466, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2878, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1248, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_time_table.sql
[2023-12-26T11:36:08.767+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=create_time_table, execution_date=20231226T113100, start_date=20231226T113608, end_date=20231226T113608
[2023-12-26T11:36:08.833+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task create_time_table (create_time_table.sql; 17261)
[2023-12-26T11:36:08.886+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T11:36:08.930+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
